import { formatCurrency } from "../components/DocumentEngine";

export function formatCompactCurrency(amount: number): string {
  if (Math.abs(amount) >= 1000000)
    return `KSh ${(amount / 1000000).toFixed(1)}M`;
  if (Math.abs(amount) >= 1000) return `KSh ${(amount / 1000).toFixed(0)}K`;
  return formatCurrency(amount);
}

export function formatPercent(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function downloadCSV(
  filename: string,
  headers: string[],
  rows: (string | number)[][],
): void {
  const csvContent = [
    headers.join(","),
    ...rows.map((row) =>
      row
        .map((cell) => {
          const str = String(cell);
          if (str.includes(",") || str.includes('"') || str.includes("\n")) {
            return `"${str.replace(/"/g, '""')}"`;
          }
          return str;
        })
        .join(","),
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}

export function printReport(title: string, contentHtml: string): void {
  const printWindow = window.open("", "_blank", "width=900,height=700");
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #0f172a; padding: 40px; }
        h1 { font-size: 24px; font-weight: 700; margin-bottom: 8px; }
        .subtitle { font-size: 13px; color: #64748b; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { text-align: left; font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.04em; padding: 10px 12px; border-bottom: 2px solid #e2e8f0; }
        td { font-size: 13px; padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
        .stat-row { display: flex; gap: 32px; margin-bottom: 24px; }
        .stat { flex: 1; }
        .stat-label { font-size: 11px; font-weight: 600; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.04em; }
        .stat-value { font-size: 20px; font-weight: 700; color: #0f172a; margin-top: 4px; }
        .badge { display: inline-block; padding: 2px 10px; border-radius: 6px; font-size: 12px; font-weight: 600; background: #eff6ff; color: #2563eb; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="subtitle">Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</div>
      ${contentHtml}
      <div class="footer">Generated by Business Management System</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 300);
}

export function exportReportPDF(
  title: string,
  stats: { label: string; value: string }[],
  tableHeaders: string[],
  tableRows: (string | number)[][],
): void {
  const tableHtml = `
    <table>
      <thead><tr>${tableHeaders.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
      <tbody>
        ${tableRows.map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("")}
      </tbody>
    </table>
  `;

  const statsHtml = `
    <div class="stat-row">
      ${stats.map((s) => `<div class="stat"><div class="stat-label">${s.label}</div><div class="stat-value">${s.value}</div></div>`).join("")}
    </div>
  `;

  printReport(title, statsHtml + tableHtml);
}
